routes/autenticacion_routes.py
from flask import Blueprint, request, flash, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
import controllers.controlador_autenticacion as controlador_autenticacion
import traceback

# Crear el blueprint para autenticación
autenticacion_bp = Blueprint('autenticacion_bp', __name__)

# Ruta para el inicio de sesión (solo maneja POST)
@autenticacion_bp.route("/login", methods=["POST"])
def login():
    email = request.form["email"]
    contrasena = request.form["contrasena"]

    print(f"Intento de inicio de sesión para el correo: {email}")  # Log para ver el correo en la terminal

    try:
        # Verificar las credenciales del usuario
        usuario = controlador_autenticacion.verificar_usuario(email, contrasena)

        if usuario:
            login_user(usuario)
            flash("Has iniciado sesión correctamente", "success")
            print(f"Usuario autenticado correctamente: {usuario.nombres} ({email})")  # Log de éxito en la terminal

            # Verificar si el usuario es Administrador basándonos en el idRol (1 = Administrador)
            if usuario.idRol == 1:
                print(f"Redirigiendo a la página de administración para el usuario: {usuario.nombres} ({email})")
                return redirect(url_for('admin_bp.menu_administrador'))  # Redirigir a 'menuAdministrador.html'

            # Si no es administrador (es cliente), redirigir al home o a la página solicitada
            next_page = request.args.get('next')
            return redirect(next_page or url_for("home"))
        else:
            flash("Correo o contraseña incorrectos", "error")
            print(f"Error: Credenciales incorrectas para {email}")  # Log de error en la terminal
            return redirect(url_for("home"))  # Redirige al home con mensaje de error
    except Exception as e:
        print(f"Error al intentar iniciar sesión para el correo {email}: {str(e)}")
        print(traceback.format_exc())  # Muestra el traceback completo del error en la terminal
        flash("Hubo un error en el sistema. Por favor, intenta nuevamente.", "error")
        return redirect(url_for("home"))

# Ruta para cerrar sesión
@autenticacion_bp.route("/logout")
@login_required
def logout():
    print(f"Usuario {current_user.email} ha cerrado sesión.")  # Log de éxito en la terminal
    logout_user()
    flash("Has cerrado sesión", "success")
    return redirect(url_for("home"))

routes/categoria_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
import controllers.controlador_categorias as controlador_categorias  # Importa el controlador de categorías
import controllers.controlador_productos as controlador_productos  # Importa el controlador de productos

# Crear el Blueprint para categorías
categoria_bp = Blueprint('categoria_bp', __name__)

# ==========================
# Funcionalidades para la página
# ==========================

# Ruta para mostrar la página de gestión de categorías
@categoria_bp.route('/menu_man_categoria', methods=["GET"])
def menu_man_categoria():
    categorias = controlador_categorias.obtener_todas_categorias()  # Llama al controlador para obtener categorías
    return render_template('menuManCategoria.html', categorias=categorias)

# Ruta para agregar una nueva categoría
@categoria_bp.route('/agregar_categoria', methods=["POST"])
def agregar_categoria():
    nombre = request.form.get('nombre')
    if not nombre:
        flash("El nombre de la categoría es obligatorio", "error")
        return redirect(url_for('categoria_bp.menu_man_categoria'))

    controlador_categorias.agregar_categoria(nombre)  # Llama al controlador para agregar la categoría
    flash("Categoría agregada exitosamente", "success")
    return redirect(url_for('categoria_bp.menu_man_categoria'))

# Ruta para actualizar una categoría
@categoria_bp.route('/actualizar_categoria', methods=["POST"])
def actualizar_categoria():
    idCategoria = request.form.get('idCategoria')
    nombre = request.form.get('nombre')
    if not idCategoria or not nombre:
        flash("Todos los campos son obligatorios", "error")
        return redirect(url_for('categoria_bp.menu_man_categoria'))

    controlador_categorias.actualizar_categoria(idCategoria, nombre)  # Llama al controlador para actualizar la categoría
    flash("Categoría actualizada exitosamente", "success")
    return redirect(url_for('categoria_bp.menu_man_categoria'))

# Ruta para eliminar una categoría desde el administrador
@categoria_bp.route("/eliminar_administrador/<int:idCategoria>", methods=["POST"])
def eliminar_categoria(idCategoria):
    try:
        # Eliminamos la categoría y la BD se encarga de eliminar los productos asociados (CASCADE)
        controlador_categorias.eliminar_categoria(idCategoria)
        flash("Categoría eliminada correctamente junto con sus productos asociados", "success")
    except Exception as e:
        flash(f"Error al eliminar la categoría: {str(e)}", "error")
    return redirect(url_for('categoria_bp.menu_man_categoria'))

# Ruta para verificar si una categoría tiene productos asociados
@categoria_bp.route('/verificar_productos/<int:idCategoria>', methods=['GET'])
def verificar_productos(idCategoria):
    try:
        # Verificamos si la categoría tiene productos asociados
        tiene_productos = controlador_productos.categoria_tiene_productos(idCategoria)
        return jsonify({"tiene_productos": tiene_productos})  # Retorna True o False
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# ==========================
# INICIO DE APIS
# ==========================

# API para listar todas las categorías en formato JSON
@categoria_bp.route("/api/listarCategorias", methods=["GET"])
def listar_categorias():
    try:
        categorias = controlador_categorias.obtener_todas_categorias()
        return jsonify({"data": categorias, "message": "Categorías obtenidas correctamente", "status": 1})
    except Exception as e:
        return jsonify({"data": [], "message": str(repr(e)), "status": -1})

# API para listar una categoría por ID en formato JSON
@categoria_bp.route("/api/listarCategoriaPorId/<int:idCategoria>", methods=["GET"])
def listar_categoria_por_id(idCategoria):
    try:
        categoria = controlador_categorias.obtener_categoria_por_id(idCategoria)
        if categoria:
            return jsonify({"data": categoria, "message": "Categoría obtenida correctamente", "status": 1})
        else:
            return jsonify({"data": [], "message": "Categoría no encontrada", "status": 0})
    except Exception as e:
        return jsonify({"data": [], "message": str(repr(e)), "status": -1})

# API para agregar una nueva categoría
@categoria_bp.route("/api/insertarCategoria", methods=["POST"])
def insertar_categoria():
    try:
        data = request.json
        nombre = data.get("nombre")
        if not nombre:
            return jsonify({"data": [], "message": "El nombre de la categoría es obligatorio", "status": -1})
        controlador_categorias.agregar_categoria(nombre)
        return jsonify({"message": "Categoría agregada correctamente", "status": 1})
    except Exception as e:
        return jsonify({"message": str(repr(e)), "status": -1})

# API para actualizar una categoría
@categoria_bp.route("/api/actualizarCategoria/<int:idCategoria>", methods=["PUT"])
def actualizar_categoria_api(idCategoria):
    try:
        data = request.json
        nombre = data.get("nombre")
        if not nombre:
            return jsonify({"data": [], "message": "El nombre de la categoría es obligatorio", "status": -1})
        controlador_categorias.actualizar_categoria(idCategoria, nombre)
        return jsonify({"message": "Categoría actualizada correctamente", "status": 1})
    except Exception as e:
        return jsonify({"message": str(repr(e)), "status": -1})

# API para eliminar una categoría
@categoria_bp.route("/api/eliminarCategoria/<int:idCategoria>", methods=["DELETE"])
def eliminar_categoria_api(idCategoria):
    try:
        controlador_categorias.eliminar_categoria(idCategoria)
        return jsonify({"message": f"Categoría con ID {idCategoria} eliminada correctamente", "status": 1})
    except Exception as e:
        return jsonify({"message": str(repr(e)), "status": -1})

routes/mispedidos_routes.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
import controllers.controlador_mispedidos as controlador_mispedidos

mispedidos_bp = Blueprint('mispedidos_bp', __name__)

# Ruta para ver los pedidos del usuario
@mispedidos_bp.route('/mispedidos')
@login_required
def mis_pedidos():
    # Obtener los pedidos del usuario actual
    pedidos = controlador_mispedidos.obtener_pedidos_usuario(current_user.id)
    return render_template('mispedidos.html', pedidos=pedidos)

# Ruta para ver los detalles de un pedido específico
@mispedidos_bp.route('/mispedidos/detalle/<int:id_pedido>')
@login_required
def detalle_pedido(id_pedido):
    # Verificar que el pedido pertenece al usuario actual
    detalles = controlador_mispedidos.obtener_detalles_pedido(id_pedido)
    if not detalles:
        flash('No tienes permiso para ver este pedido o el pedido no existe.', 'danger')
        return redirect(url_for('mispedidos_bp.mis_pedidos'))
    return render_template('detalle_pedido.html', detalles=detalles, id_pedido=id_pedido)

routes/rol_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
import controllers.controlador_roles as controlador_roles  # Importa el controlador de roles

from flask_jwt_extended import jwt_required, get_jwt_identity

# Crear el Blueprint para roles
rol_bp = Blueprint('rol_bp', __name__)

# Ruta para mostrar la página de gestión de roles
@rol_bp.route('/menu_man_rol', methods=["GET"])
def menu_man_rol():
    roles = controlador_roles.obtener_roles()  # Llama al controlador para obtener roles
    return render_template('menuManRol.html', roles=roles)

# Ruta para agregar un nuevo rol
@rol_bp.route('/agregar_rol', methods=["POST"])
def agregar_rol():
    nombre = request.form.get('nombre')
    if not nombre:
        flash("El nombre del rol es obligatorio", "error")
        return redirect(url_for('rol_bp.menu_man_rol'))

    controlador_roles.agregar_rol(nombre)  # Llama al controlador para agregar el rol
    flash("Rol agregado exitosamente", "success")
    return redirect(url_for('rol_bp.menu_man_rol'))

# Ruta para actualizar un rol
@rol_bp.route('/actualizar_rol', methods=["POST"])
def actualizar_rol():
    idRol = request.form.get('idRol')
    nombre = request.form.get('nombre')
    if not idRol or not nombre:
        flash("Todos los campos son obligatorios", "error")
        return redirect(url_for('rol_bp.menu_man_rol'))

    controlador_roles.actualizar_rol(idRol, nombre)  # Llama al controlador para actualizar el rol
    flash("Rol actualizado exitosamente", "success")
    return redirect(url_for('rol_bp.menu_man_rol'))

# Ruta para eliminar un rol
@rol_bp.route('/eliminar_rol/<int:idRol>', methods=["POST"])
def eliminar_rol(idRol):
    controlador_roles.eliminar_rol(idRol)  # Llama al controlador para eliminar el rol
    flash("Rol eliminado exitosamente", "success")
    return redirect(url_for('rol_bp.menu_man_rol'))

# ==========================
# INICIO DE APIS
# ==========================

# API para listar todos los roles en formato JSON
@rol_bp.route("/api/listarRoles", methods=["GET"])
@jwt_required()
def listar_roles():
    try:
        roles = controlador_roles.obtener_roles()
        return jsonify({"data": roles, "message": "Roles obtenidos correctamente", "status": 1})
    except Exception as e:
        return jsonify({"data": [], "message": str(repr(e)), "status": -1})

# API para listar un rol por ID en formato JSON
@rol_bp.route("/api/listarRolPorId/<int:idRol>", methods=["GET"])
@jwt_required()
def listar_rol_por_id(idRol):
    try:
        rol = controlador_roles.obtener_rol_por_id(idRol)
        if rol:
            return jsonify({"data": rol, "message": "Rol obtenido correctamente", "status": 1})
        else:
            return jsonify({"data": [], "message": "Rol no encontrado", "status": 0})
    except Exception as e:
        return jsonify({"data": [], "message": str(repr(e)), "status": -1})

# API para agregar un nuevo rol
@rol_bp.route("/api/insertarRol", methods=["POST"])
@jwt_required()
def insertar_rol():
    try:
        data = request.json
        nombre = data.get("nombre")
        if not nombre:
            return jsonify({"data": [], "message": "El nombre del rol es obligatorio", "status": -1})
        controlador_roles.agregar_rol(nombre)
        return jsonify({"message": "Rol agregado correctamente", "status": 1})
    except Exception as e:
        return jsonify({"message": str(repr(e)), "status": -1})

# API para actualizar un rol
@rol_bp.route("/api/actualizarRol/<int:idRol>", methods=["PUT"])
@jwt_required()
def actualizar_rol_api(idRol):
    try:
        data = request.json
        nombre = data.get("nombre")
        if not nombre:
            return jsonify({"data": [], "message": "El nombre del rol es obligatorio", "status": -1})
        controlador_roles.actualizar_rol(idRol, nombre)
        return jsonify({"message": "Rol actualizado correctamente", "status": 1})
    except Exception as e:
        return jsonify({"message": str(repr(e)), "status": -1})

# API para eliminar un rol
@rol_bp.route("/api/eliminarRol/<int:idRol>", methods=["DELETE"])
@jwt_required()
def eliminar_rol_api(idRol):
    try:
        controlador_roles.eliminar_rol(idRol)
        return jsonify({"message": f"Rol con ID {idRol} eliminado correctamente", "status": 1})
    except Exception as e:
        return jsonify({"message": str(repr(e)), "status": -1})

templates/menuManCategoria.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Categorías</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/menuAdministrador.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='img/image 19.webp') }}" type="QORI-PERU">
</head>

<body>

    <div class="container-fluid">
        <div class="row">
            <!-- Menú Lateral -->
            <div class="col-md-2 d-flex flex-column sidebar">
                <!-- Logo -->
                <div class="logo-container">
                    <a href="{{ url_for('home') }}">
                        <img src="{{ url_for('static', filename='img/logo.webp') }}" alt="Logo" class="img-fluid logo">
                    </a>
                </div>

                <!-- Opciones del Menú -->
                <ul class="nav flex-column flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('rol_bp.menu_man_rol') }}"><i class="fas fa-user-tag"></i>
                            Roles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('usuario_bp.menu_man_usuario') }}"><i
                                class="fas fa-users"></i> Usuarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('producto_bp.menu_man_producto') }}"><i
                                class="fas fa-box"></i> Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('categoria_bp.menu_man_categoria') }}"><i
                                class="fas fa-tags"></i> Categorías</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('resena_bp.menu_man_resena') }}"><i
                                class="fas fa-star"></i> Reseñas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('tarjetaAdmin_bp.menu_man_tarjeta') }}"><i
                                class="fas fa-credit-card"></i> Tarjetas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('pedido_bp.menu_man_pedido') }}"><i
                                class="fas fa-truck"></i> Pedidos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('pago_bp.menu_man_pago') }}">
                            <i class="fas fa-credit-card"></i> Pagos
                        </a>
                    </li>
                </ul>

                <!-- Usuario y Cerrar Sesión -->
                <div class="user-info mt-auto">
                    <span class="nav-link">{{ current_user.nombres }}</span>
                    <a href="{{ url_for('autenticacion_bp.logout') }}" class="nav-link nav-link-underline">
                        <i class="fas fa-sign-out-alt"></i> Cerrar Sesión
                    </a>
                </div>
            </div>

            <!-- Contenido principal -->
            <div class="col-md-10 mt-4">
                <h1 class="mb-4">Gestión de Categorías</h1>
                <!-- Botón para abrir el modal de agregar categoría -->
                <a href="#" class="btn btn-success mb-3" data-bs-toggle="modal"
                    data-bs-target="#agregarCategoriaModal">Agregar Categoría</a>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Creado El</th>
                            <th>Modificado El</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for categoria in categorias %}
                        <tr>
                            <td>{{ categoria[0] }}</td> <!-- idCategoria -->
                            <td>{{ categoria[1] }}</td> <!-- nombre -->
                            <td>{{ categoria[2] }}</td> <!-- fechaCreacion -->
                            <td>{{ categoria[3] }}</td> <!-- fechaModificacion -->
                            <td>
                                <a href="#" class="btn btn-warning" data-bs-toggle="modal"
                                    data-bs-target="#editarCategoriaModal" data-id="{{ categoria[0] }}"
                                    data-nombre="{{ categoria[1] }}">Editar</a>
                                <button type="button" class="btn btn-danger"
                                    onclick="confirmarEliminacionCategoria('{{ categoria[0] }}')">
                                    Eliminar
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Modal de Confirmar para Eliminar Categoría -->
    <div class="modal fade" id="confirmarEliminacionModal" tabindex="-1"
        aria-labelledby="confirmarEliminacionModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmarEliminacionModalLabel">Confirmar Eliminación</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="mensaje-confirmacion">
                    <!-- Este mensaje se actualizará dinámicamente -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <form id="eliminarCategoriaForm" method="POST">
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal para Editar Categoría -->
    <div class="modal fade" id="editarCategoriaModal" tabindex="-1" aria-labelledby="editarCategoriaModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editarCategoriaModalLabel">Editar Categoría</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="editarCategoriaForm" method="POST"
                        action="{{ url_for('categoria_bp.actualizar_categoria') }}">
                        <div class="mb-3">
                            <label for="nombre" class="form-label">Nombre</label>
                            <input type="text" class="form-control" id="nombre" name="nombre">
                        </div>
                        <input type="hidden" id="idCategoria" name="idCategoria">
                        <button type="submit" class="btn btn-primary">Guardar cambios</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal para Agregar Categoría -->
    <div class="modal fade" id="agregarCategoriaModal" tabindex="-1" aria-labelledby="agregarCategoriaModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="agregarCategoriaModalLabel">Agregar Categoría</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="agregarCategoriaForm" method="POST"
                        action="{{ url_for('categoria_bp.agregar_categoria') }}">
                        <div class="mb-3">
                            <label for="nombre" class="form-label">Nombre</label>
                            <input type="text" class="form-control" id="nombre" name="nombre" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Agregar Categoría</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Parte para llamar a confirmar eliminación de una categoría
        function confirmarEliminacionCategoria(idCategoria) {
            // Hacer una petición para verificar si la categoría tiene productos asociados
            fetch(`/categoria/verificar_productos/${idCategoria}`)
                .then(response => response.json())
                .then(data => {
                    const mensajeConfirmacion = document.getElementById('mensaje-confirmacion');
                    const formEliminarCategoria = document.getElementById('eliminarCategoriaForm');
                    // Si la categoría tiene productos, mostrar una advertencia adicional
                    if (data.tiene_productos) {
                        mensajeConfirmacion.textContent = "La categoría tiene productos asociados. Al eliminarla, también se eliminarán los productos. ¿Estás seguro que deseas continuar?";
                    } else {
                        mensajeConfirmacion.textContent = "¿Estás seguro que deseas eliminar esta categoría? Esta acción no se puede deshacer.";
                    }
                    // Actualizar la acción del formulario
                    formEliminarCategoria.action = `/categoria/eliminar_administrador/${idCategoria}`;
                    // Mostrar el modal
                    const eliminarModal = new bootstrap.Modal(document.getElementById('confirmarEliminacionModal'));
                    eliminarModal.show();
                })
                .catch(error => {
                    console.error('Error al verificar productos:', error);
                });
        }
    </script>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://kit.fontawesome.com/79be0d4522.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>